//! Local JSON Schema validation against the bundled event-type schemas.
//!
//! Mirrors the TS reference at `src/cli/lib/schema-validate.ts`:
//! `validateEventLocally(typeId, data) → ValidationIssue[]`. The Rust
//! port returns `Option<Vec<ValidationIssue>>`:
//!   - `None`              — unknown type id (TS guards via `isKnownEventType`)
//!   - `Some(Vec::new())`  — valid
//!   - `Some(issues)`      — invalid; path is dot-joined for TS parity
//!
//! Bundle is generated by `scripts/generate-schema-bundle.mjs` from
//! `@magic-ingredients/no-tickets-schemas` Zod source. The canonical
//! source long-term is the GitHub Release asset produced by the sister
//! fix `client-roadmap-server-prerequisites` Tasks 6+7 in the
//! no-tickets-service repo. Swapping `include_str!` for a `build.rs`
//! fetch-and-verify pass is a follow-up; the validator API surface
//! here doesn't change.

use std::collections::BTreeMap;
use std::sync::OnceLock;

use jsonschema::Validator;
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct ValidationIssue {
    pub path: String,
    pub message: String,
}

const BUNDLE_JSON: &str =
    include_str!("../schemas/event-types.bundle.json");

#[derive(Debug, Deserialize)]
struct BundleFile {
    #[serde(rename = "bundleVersion")]
    bundle_version: String,
    // BTreeMap preserves the alphabetised key order from the generator
    // (which sorts keys explicitly), which `known_type_ids` returns
    // verbatim.
    schemas: BTreeMap<String, Value>,
}

struct CompiledBundle {
    version: &'static str,
    /// Sorted vec of (type_id, compiled_validator). Vec rather than
    /// HashMap so `known_type_ids` can return slices into stable storage
    /// at no extra cost.
    entries: Vec<(String, Validator)>,
}

fn bundle() -> &'static CompiledBundle {
    static CELL: OnceLock<CompiledBundle> = OnceLock::new();
    CELL.get_or_init(|| {
        let parsed: BundleFile =
            serde_json::from_str(BUNDLE_JSON).expect("bundle JSON parses");
        // Leak the version string so we can hand out &'static str.
        // One-time allocation per process — trivial.
        let version: &'static str = Box::leak(parsed.bundle_version.into_boxed_str());
        let mut entries: Vec<(String, Validator)> = parsed
            .schemas
            .into_iter()
            .map(|(type_id, schema)| {
                let validator = jsonschema::draft202012::new(&schema)
                    .unwrap_or_else(|e| {
                        panic!("schema for {type_id:?} failed to compile: {e}")
                    });
                (type_id, validator)
            })
            .collect();
        // BTreeMap already sorted; the .collect preserves order. Keep
        // the explicit sort to be defensive against bundle format
        // changes.
        entries.sort_by(|a, b| a.0.cmp(&b.0));
        CompiledBundle { version, entries }
    })
}

/// Version of the upstream `@magic-ingredients/no-tickets-schemas`
/// package the bundle was generated from. Pinned at the bundle file
/// level (`bundleVersion` field); resolved lazily on first call.
pub fn bundle_version() -> &'static str {
    bundle().version
}

/// Sorted list of every event-type id the bundle knows about.
pub fn known_type_ids() -> Vec<&'static str> {
    bundle().entries.iter().map(|(k, _)| k.as_str()).collect()
}

/// Validate `data` against the bundled schema for `type_id`.
///
/// - `None` — `type_id` is not in the bundle (caller should surface
///   `unknown_event_type`).
/// - `Some(Vec::new())` — data validates cleanly.
/// - `Some(issues)` — data fails validation; each issue carries a
///   dot-joined `path` (matching TS `validateEventLocally`'s shape)
///   and a human-readable `message`.
pub fn validate(type_id: &str, data: &Value) -> Option<Vec<ValidationIssue>> {
    let validator = bundle()
        .entries
        .iter()
        .find_map(|(k, v)| (k == type_id).then_some(v))?;

    let issues: Vec<ValidationIssue> = validator
        .iter_errors(data)
        .map(|err| ValidationIssue {
            path: json_pointer_to_dot_path(&err.instance_path().to_string()),
            message: err.to_string(),
        })
        .collect();
    Some(issues)
}

/// Convert a JSON Pointer (`/foo/bar`, `/items/0/name`) to the
/// dot-joined path style TS uses (`foo.bar`, `items.0.name`). Empty
/// pointer (i.e. error at the document root) becomes the empty string.
fn json_pointer_to_dot_path(pointer: &str) -> String {
    let trimmed = pointer.strip_prefix('/').unwrap_or(pointer);
    if trimmed.is_empty() {
        return String::new();
    }
    // RFC 6901 escapes `/` as `~1` and `~` as `~0` inside path segments.
    // Field names in this codebase don't include either character, but
    // unescape defensively so a future schema change doesn't surprise us.
    trimmed
        .split('/')
        .map(|seg| seg.replace("~1", "/").replace("~0", "~"))
        .collect::<Vec<_>>()
        .join(".")
}

#[cfg(test)]
mod internal_tests {
    use super::*;

    #[test]
    fn json_pointer_root_to_empty_string() {
        assert_eq!(json_pointer_to_dot_path(""), "");
        assert_eq!(json_pointer_to_dot_path("/"), "");
    }

    #[test]
    fn json_pointer_single_segment() {
        assert_eq!(json_pointer_to_dot_path("/taskId"), "taskId");
    }

    #[test]
    fn json_pointer_nested_segments() {
        assert_eq!(json_pointer_to_dot_path("/outer/inner"), "outer.inner");
    }

    #[test]
    fn json_pointer_array_index_segment() {
        assert_eq!(json_pointer_to_dot_path("/items/0/name"), "items.0.name");
    }
}
