//! Validator parity tests for the bundled JSON Schemas.
//!
//! Reference: `src/cli/lib/schema-validate.ts::validateEventLocally` (TS).
//! The Rust port returns `Option<Vec<ValidationIssue>>` instead of TS's
//! "throw-on-unknown after isKnownEventType guard" pattern — the
//! `None` arm makes the unknown case explicit at the type level rather
//! than relying on caller-side narrowing.
//!
//! Bundle generated by `scripts/generate-schema-bundle.mjs` from
//! `@magic-ingredients/no-tickets-schemas` Zod source.

use serde_json::{Value, json};

use nt_schemas::{ValidationIssue, bundle_version, known_type_ids, validate};

// ─── Bundle integrity ──────────────────────────────────────────────────────

/// Every event type id that exists in the upstream `byTypeId` map at
/// schemas-package v0.2.0 must be present in the bundle. Pinning the
/// full list catches:
/// - A regenerate that loses schemas (transient generator bug).
/// - The upstream `byTypeId` adding a new type without re-bundling.
#[test]
fn bundle_contains_every_expected_type_id() {
    let expected = [
        "ai.completion.recorded.v1",
        "ai.review.completed.v1",
        "ai.task.completed.v1",
        "product.epic.created.v1",
        "product.feature.archived.v1",
        "product.feature.assigned.v1",
        "product.feature.created.v1",
        "product.feature.status_changed.v1",
        "product.task.assigned.v1",
        "product.task.created.v1",
        "product.task.status_changed.v1",
    ];
    let known = known_type_ids();
    assert_eq!(
        known, expected,
        "bundle keyset must match the upstream byTypeId map exactly (in sorted order)",
    );
}

#[test]
fn bundle_version_matches_upstream_schemas_package() {
    assert_eq!(
        bundle_version(),
        "0.2.0",
        "bundle_version() must mirror the @magic-ingredients/no-tickets-schemas version embedded at generation time",
    );
}

// ─── Lookup behaviour ──────────────────────────────────────────────────────

#[test]
fn unknown_type_id_returns_none() {
    let r = validate("does.not.exist.v1", &json!({}));
    assert!(r.is_none(), "unknown type id must return None, got {r:?}");
}

#[test]
fn empty_type_id_returns_none() {
    let r = validate("", &json!({}));
    assert!(r.is_none(), "empty type id must return None");
}

// ─── Happy path: valid payloads pass with empty issue list ────────────────

fn valid_ai_task_completed() -> Value {
    json!({
        "taskId": "task-1",
        "sessionId": "session-1",
        "startedAt": "2026-05-01T00:00:00.000Z",
        "completedAt": "2026-05-01T00:00:01.000Z",
        "durationMs": 1000,
        "outcome": "success",
        "callCount": 1,
    })
}

#[test]
fn valid_ai_task_completed_returns_empty_issues() {
    let issues = validate("ai.task.completed.v1", &valid_ai_task_completed());
    assert_eq!(
        issues,
        Some(Vec::<ValidationIssue>::new()),
        "valid payload must return Some(empty vec)",
    );
}

#[test]
fn valid_product_feature_created_returns_empty_issues() {
    // Per the bundled schema: required = [featureId, projectId, title, status].
    // Optional: parentId, assignee, assigneeType. additionalProperties: false.
    let payload = json!({
        "featureId": "f-1",
        "projectId": "p-1",
        "title": "X",
        "status": "ideation",
    });
    let issues = validate("product.feature.created.v1", &payload);
    assert_eq!(
        issues,
        Some(Vec::<ValidationIssue>::new()),
        "valid product.feature.created.v1 must return Some(empty vec); got {issues:?}",
    );
}

#[test]
fn valid_product_task_status_changed_returns_empty_issues() {
    // Per the bundled schema: required = [taskId, fromStatus, toStatus].
    // (TS Zod uses fromStatus/toStatus, not from/to. Both reuse
    // productStatusSchema's enum: ideation/development/testing/review/done.)
    let payload = json!({
        "taskId": "t-1",
        "fromStatus": "ideation",
        "toStatus": "development",
    });
    let issues = validate("product.task.status_changed.v1", &payload);
    assert_eq!(
        issues,
        Some(Vec::<ValidationIssue>::new()),
        "valid product.task.status_changed.v1 must return Some(empty vec); got {issues:?}",
    );
}

// ─── Failure modes: missing required, wrong type, format violations ───────

#[test]
fn missing_required_field_is_reported_with_field_path() {
    let mut payload = valid_ai_task_completed();
    payload.as_object_mut().unwrap().remove("taskId");
    let issues = validate("ai.task.completed.v1", &payload).expect("known type id");
    assert!(!issues.is_empty(), "missing required taskId must produce issues");
    assert!(
        issues.iter().any(|i| i.path == "taskId" || i.message.contains("taskId")),
        "issue must name the missing field `taskId`; got {issues:?}",
    );
}

#[test]
fn wrong_field_type_is_reported() {
    let mut payload = valid_ai_task_completed();
    payload["durationMs"] = json!("not a number");
    let issues = validate("ai.task.completed.v1", &payload).expect("known type id");
    assert!(!issues.is_empty(), "wrong type for durationMs must produce issues");
    assert!(
        issues.iter().any(|i| i.path == "durationMs"),
        "issue path must point at `durationMs`; got {issues:?}",
    );
}

#[test]
fn enum_violation_is_reported() {
    let mut payload = valid_ai_task_completed();
    payload["outcome"] = json!("definitely_not_an_outcome");
    let issues = validate("ai.task.completed.v1", &payload).expect("known type id");
    assert!(!issues.is_empty(), "bad enum value must produce issues");
    assert!(
        issues.iter().any(|i| i.path == "outcome"),
        "issue path must point at `outcome`; got {issues:?}",
    );
}

#[test]
fn min_length_violation_is_reported() {
    let mut payload = valid_ai_task_completed();
    payload["taskId"] = json!(""); // z.string().min(1) → minLength: 1
    let issues = validate("ai.task.completed.v1", &payload).expect("known type id");
    assert!(
        !issues.is_empty(),
        "empty taskId must violate minLength and produce issues",
    );
    assert!(
        issues.iter().any(|i| i.path == "taskId"),
        "issue path must point at `taskId`; got {issues:?}",
    );
}

#[test]
fn additional_properties_are_rejected() {
    let mut payload = valid_ai_task_completed();
    payload["unexpectedExtra"] = json!(42);
    let issues = validate("ai.task.completed.v1", &payload).expect("known type id");
    assert!(
        !issues.is_empty(),
        ".strict() Zod schemas convert to additionalProperties=false; extras must be rejected",
    );
}

#[test]
fn date_time_format_violation_is_reported() {
    let mut payload = valid_ai_task_completed();
    payload["startedAt"] = json!("not a real iso8601 timestamp");
    let issues = validate("ai.task.completed.v1", &payload).expect("known type id");
    assert!(
        !issues.is_empty(),
        "bad date-time format must produce issues",
    );
    assert!(
        issues.iter().any(|i| i.path == "startedAt"),
        "issue path must point at `startedAt`; got {issues:?}",
    );
}

// ─── TS parity: issue.path is dot-joined (TS does path.join('.')) ─────────

/// Nested-path test using a synthetic deep payload. TS produces paths
/// like "outer.inner" (array join with '.'). The jsonschema crate
/// produces a JSON Pointer like "/outer/inner" — the Rust port must
/// translate to dot-form for TS parity. Even without a deeply-nested
/// schema in the bundle, the TOP-LEVEL field path must be just the
/// field name (no leading '/', no leading '.').
#[test]
fn issue_path_is_dot_joined_for_ts_parity() {
    let mut payload = valid_ai_task_completed();
    payload.as_object_mut().unwrap().remove("taskId");
    let issues = validate("ai.task.completed.v1", &payload).expect("known type id");
    for issue in &issues {
        assert!(
            !issue.path.starts_with('/'),
            "issue path must NOT be JSON Pointer style; got {:?}",
            issue.path,
        );
        assert!(
            !issue.path.starts_with('.'),
            "issue path must NOT have leading dot; got {:?}",
            issue.path,
        );
    }
}

// ─── ValidationIssue serialises with TS-shape (path, message) ─────────────

#[test]
fn validation_issue_serialises_with_ts_shape() {
    let issue = ValidationIssue {
        path: "outer.inner".to_string(),
        message: "expected string".to_string(),
    };
    let json = serde_json::to_value(&issue).expect("serialize");
    assert_eq!(json["path"], "outer.inner");
    assert_eq!(json["message"], "expected string");
    // TS interface is `{ path, message }` — two fields, no extras.
    assert_eq!(
        json.as_object().unwrap().len(),
        2,
        "ValidationIssue must serialise to exactly two fields",
    );
}
